name: cdgaussian
channels:
  - pytorch
  - nvidia
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
dependencies:
  - plyfile
  - python=3.8
  - pip=23.0.1
  - tqdm
  - psutil
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - torchvision=0.15.2
  - setuptools=69.1.1
  - mkl==2024.0
  - pandas
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - -i https://pypi.tuna.tsinghua.edu.cn/simple
